AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploys a serverless TODOS application - using serverless dynamoDB table "todos-table" as database, serverless Lambda  function "DDBHandlerFunction" as database handler (stored in s3 bucket), and APIGateways to trigger the Lambda function.
  
Globals:
  Function:
    Timeout: 10

Resources:
  DDBHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://idob-zengo-function/index.zip
      Handler: index.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodosTable
      Events:
        GetAllTodos:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: GET
        CreateTodo:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: PUT

  TodosTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: todo
        Type: String
      TableName: todos-table
